# Incremental mypy adoption proposal
# We integrate mypy gradually and fix errors in small batches.
# 1) Keep a baseline of existing issues.
# 2) Prioritize critical modules first (services/handlers/models).
# 3) Require new or heavily changed code to pass mypy.
# 4) Expand CI coverage step-by-step as error count decreases.
#
# IDE recommendation:
# Install "Mypy Type Checker" for inline diagnostics:
# https://marketplace.cursorapi.com/items/?itemName=ms-python.mypy-type-checker
# https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker
# https://plugins.jetbrains.com/plugin/25888-mypy
#
# NOTE: Mypy in IDE has some delays because it runs a little slowly.

[mypy]
mypy_path = src
# In future good idea to enable strict mode, after fixing all type issues
strict = False
warn_return_any = True
warn_unused_configs = True
explicit_package_bases = True
check_untyped_defs = True
follow_untyped_imports = True
exclude = ^(DEBUG/|tests/|patches/|cli/|\.venv/)

# These imports provide some bugs on mypy side
# Like when mypy raise error for commented out code
[mypy-modular_sdk.*]
follow_imports = skip
