MAPPING = {
    "aws.access-analyzer": [
        "epam-aws-276-iam_access_analyzer_is_enabled",
        "epam-aws-426-iam_access_analyzer_findings_are_reviewed_and_resolved",
    ],
    "aws.acm": [
        "epam-aws-567-acm_without_tag_information",
        "epam-aws-241-acm_has_no_unused_certificates",
        "epam-aws-243-invalid_or_failed_certificates_are_removed_from_acm",
        "epam-aws-249-expired_certificates_are_removed_from_acm",
        "epam-aws-922-acm_certificate_transparency_logging_enabled",
        "epam-aws-821-acm_certificate_not_using_a_minimum_of_2048-bit_key_for_rsa_certificate",
        "epam-aws-240-acm_has_certificates_single_domain_names",
    ],
    "aws.apigateway": [
        "epam-aws-549-api_gateway_http_api_and_websocket_api_logs_not_enabled",
        "epam-aws-398-rest_api_gateway_cache_enabled",
        "epam-aws-322-api_gateway_rest_api_stages_ssl_certificates_configured",
        "epam-aws-323-rest_api_aws_x_ray_enabled",
        "epam-aws-524-rest_api_gateway_access_logging_enabled",
        "epam-aws-526-rest_api_gateway_logs_set_correctly",
        "epam-aws-396-rest_api_gateway_is_protected_by_waf",
        "epam-aws-397-rest_api_gateway_contend_encoding_enabled",
        "epam-aws-292-api_gateway_rest_api_encryption_at_rest",
        "epam-aws-251-api_key_is_required_on_method_request",
        "epam-aws-250-rest_api_gateway_is_set_to_private",
    ],
    "aws.appflow": [
        "epam-aws-399-appflow_encrypted_with_kms_cmk",
        "epam-aws-568-app_flow_without_tag_information",
    ],
    "aws.autoscaling": [
        "epam-aws-433-autoscaling_group_has_associated_elb",
        "epam-aws-438-autoscaling_group_has_valid_configuration",
        "epam-aws-436-autoscaling_group_utilize_multi_az",
        "epam-aws-198-autoscaling_group_health_checks",
        "epam-aws-702-autoscaling_groups_capacity_rebalancing_enabled",
        "epam-aws-531-autoscaling_launch_config_public_ip_disabled",
        "epam-aws-569-auto_scaling_group_without_tag_information",
        "epam-aws-904-autoscaling_launch_config_hop_limit",
        "epam-aws-703-autoscaling_launchconfig_requires_imdsv2",
        "epam-aws-430-autoscaling_group_cooldown_period",
    ],
    "aws.backup": [
        "epam-aws-442-backups_encrypted_with_kms_customer_master_keys",
        "epam-aws-440-backup_service_compliant_lifecycle_enabled",
    ],
    "aws.batch": [],
    "aws.clouddirectory": [],
    "aws.cloudformation": [
        "epam-aws-711-cloudformation_stack_notification_check",
        "epam-aws-574-cloudformation_stacks_without_tag_information",
        "epam-aws-710-cloudformation_stack_drift_detection_check",
    ],
    "aws.cloudfront": [
        "epam-aws-444-use_secure_ssl_protocols_between_cloudfront_origin",
        "epam-aws-210-cloud_front_waf_integration",
        "epam-aws-575-cloudfront_distributions_without_tag_information",
        "epam-aws-238-cloudfront_web_distributions_with_geo_restriction_enabled",
        "epam-aws-326-cloudfront_origin_failover_configured",
        "epam-aws-938-cloudfront_encryption_in_transit",
        "epam-aws-448-cloudfront_distribution_fieldlevel_encryption",
        "epam-aws-190-encrypted_connection_between_cloudfront_origin",
        "epam-aws-712-cloudfront_sni_enabled",
        "epam-aws-242-cloudfront_distribution_access_logging",
        "epam-aws-324-cloudfront_default_root_object_configured",
        "epam-aws-237-cloudfront_web_distributions_use_custom_ssl_certificates",
        "epam-aws-090-use_secure_ciphers_in_cloudfront_distribution",
        "epam-aws-325-cloudfront_origin_access_identity_enabled",
    ],
    "aws.cloudhsm": [],
    "aws.cloudsearch": [],
    "aws.cloudtrail": [
        "epam-aws-227-network_access_control_lists_changes_alarm_exists",
        "epam-aws-207-cloudtrail_configuration_changes_alarm_exists",
        "epam-aws-547-cloudtrail_logs_data_events",
        "epam-aws-209-cmk_key_disabling_or_deletion_alarm_exists",
        "epam-aws-176-cloudtrail_log_validation_enabled",
        "epam-aws-578-cloudtrail_without_tag_information",
        "epam-aws-184-cloudtrail_logs_encrypted_using_KMS_CMKs",
        "epam-aws-211-cloudtrail_bucket_logging_enabled",
        "epam-aws-282-bucket_object-level_logging_for_write_enabled",
        "epam-aws-204-sign_in_without_mfa_alarm_exist",
        "epam-aws-523-cloudtrail_security_trail_enabled",
        "epam-aws-283-bucket_object-level_logging_for_read_enabled",
        "epam-aws-175-cloudtrail_enabled_in_all_regions",
        "epam-aws-225-aws_config_configuration_changes_alarm_exists",
        "epam-aws-226-security_group_changes_alarm_exists",
        "epam-aws-205-root_usage_alarm_exists",
        "epam-aws-208-console_auth_failure_alarm_exists",
        "epam-aws-224-s3_bucket_policy_changes_alarm_exists",
        "epam-aws-206-iam_policy_changes_alarm_exist",
        "epam-aws-179-cloudtrail_integrated_with_cloudwatch",
        "epam-aws-452-cloudtrail_logs_management_events",
        "epam-aws-230-vpc_changes_alarm_exists",
        "epam-aws-192-unauthorized_api_calls_alarm_exists",
        "epam-aws-228-network_gateways_changes_alarm_exists",
        "epam-aws-229-route_table_changes_alarm_exists",
    ],
    "aws.codeartifact": [],
    "aws.codebuild": [
        "epam-aws-718-codebuild_project_environment_privileged_check",
        "epam-aws-197-codebuild_project_source_repo_url_check",
        "epam-aws-717-codebuild_project_artifact_encryption",
        "epam-aws-218-codebuild_environment_variables_contain_text_credentials",
        "epam-aws-719-codebuild_project_logging_enabled",
    ],
    "aws.codecommit": [],
    "aws.codedeploy": [
        "epam-aws-722-codedeploy_ec2_minimum_healthy_hosts_configured",
        "epam-aws-723-codedeploy_lambda_allatonce_traffic_shift_disabled",
        "epam-aws-721-codedeploy_auto_rollback_monitor_enabled",
    ],
    "aws.codepipeline": [],
    "aws.cognito-identity": [],
    "aws.cognito-idp": [],
    "aws.config": ["epam-aws-183-config_enabled_all_regions"],
    "aws.directconnect": [],
    "aws.dlm": [],
    "aws.dms": [
        "epam-aws-470-dms_replication_instances_encrypted_with_kms_cmk",
        "epam-aws-482-dms_multi_az_enabled",
        "epam-aws-584-dms_without_tag_information",
        "epam-aws-461-dms_latest_version",
        "epam-aws-469-dms_auto_minor_version_upgrade",
        "epam-aws-327-dms_replication_not_public",
    ],
    "aws.ds": [
        "epam-aws-538-ds_directory_not_open_to_large_scope",
        "epam-aws-546-workspaces_radius_server_uses_strongest_security_protocol",
    ],
    "aws.dynamodb": [
        "epam-aws-330-dynamodb_dax_encryption_enabled",
        "epam-aws-256-dynamodb_is_encrypted_using_managed_cmk",
        "epam-aws-329-dynamodb_tables_pitr_enabled",
        "epam-aws-328-dynamodb_tables_autoscaling_enabled",
    ],
    "aws.ec2": [
        "epam-aws-109-prevent_0-65535_ingress_and_all",
        "epam-aws-293-security_group_ingress_is_restricted_traffic_to_port_20",
        "epam-aws-374-eks_clusters_security_group_traffic_restricted",
        "epam-aws-114-security_group_ingress_is_restricted_traffic_to_mongodb_port_27017",
        "epam-aws-188-default_security_group_every_vpc_restricts_all_traffic",
        "epam-aws-119-security_group_ingress_is_restricted_traffic_to_postgresql_port_5432",
        "epam-aws-734-ec2_instance_detailed_monitoring_enabled",
        "epam-aws-110-security_group_ingress_is_restricted_traffic_to_dns_port_53",
        "epam-aws-489-unused_ebs_volumes",
        "epam-aws-285-no_acls_allow_ingress_for_everyone_to_remote_server_administration_ports",
        "epam-aws-740-ec2_transit_gateway_auto_vpc_attach_disabled",
        "epam-aws-545-workspaces_api_requests_flow_through_vpc_endpoint",
        "epam-aws-371-ec2_managed_instance_association_compliance_status_check",
        "epam-aws-552-ebs_snapshot_without_tag_information",
        "epam-aws-558-network_acl_without_tag_information",
        "epam-aws-103-instance_without_termination_protection",
        "epam-aws-409-vpc_unused_internet_gateway",
        "epam-aws-033-ensure_vpc_flow_logging_enabled_for_every_vpc",
        "epam-aws-560-security_group_without_tag_information",
        "epam-aws-112-security_group_ingress_is_restricted_traffic_to_http_port_80",
        "epam-aws-310-security_group_ingress_is_restricted_traffic_to_port_143",
        "epam-aws-115-security_group_ingress_is_restricted_traffic_to_mysql_db_port_3306",
        "epam-aws-289-ebs_volume_without_encrypt",
        "epam-aws-199-unused_eip_should_be_removed",
        "epam-aws-120-security_group_ingress_is_restricted_traffic_to_smtp_port_25",
        "epam-aws-394-transit_gateway_default_route_table_association_disabled",
        "epam-aws-316-security_group_ingress_is_restricted_traffic_to_port_8080",
        "epam-aws-105-rds_instance_with_no_backups",
        "epam-aws-334-vpc_unused_network_acl",
        "epam-aws-268-clb_with_sensitive_service_is_exposed_to_entire_internet",
        "epam-aws-196-unused_ec2_security_groups",
        "epam-aws-203-ebs_snapshots_not_publicly_restorable",
        "epam-aws-121-security_group_ingress_is_restricted_traffic_to_telnet_port_23",
        "epam-aws-305-rds_database_instance_engine_no_default_ports",
        "epam-aws-372-ec2_instance_imdsv2_enabled",
        "epam-aws-270-alb_with_sensitive_service_is_exposed_to_entire_internet",
        "epam-aws-116-security_group_ingress_is_restricted_traffic_to_netbios_ssn_port_139",
        "epam-aws-312-security_group_ingress_is_restricted_traffic_to_mssql_ports",
        "epam-aws-335-ec2_instance_should_not_use_multiple_eni",
        "epam-aws-266-public_instance_with_sensitive_service_is_exposed_to_entire_internet",
        "epam-aws-395-transit_gateway_default_route_table_propagation_disabled",
        "epam-aws-488-ebs_snapshot_encrypted",
        "epam-aws-231-vpc-subnets_automatic_public_ip_assignment",
        "epam-aws-314-security_group_ingress_is_restricted_traffic_to_port_5500",
        "epam-aws-487-ebs_volume_encrypted_with_kms_cmk",
        "epam-aws-565-vpc_without_tag_information",
        "epam-aws-333-ec2_service_use_vpc_endpoints",
        "epam-aws-248-k8s_cluster_network_firewall_inbound_rule_permissive_to_all_traffic",
        "epam-aws-244-ecs_cluster_at_rest_encryption",
        "epam-aws-564-peering_connection_without_tag_information",
        "epam-aws-543-workspaces_primary_interface_ports_not_open_to_all_inbound_traffic",
        "epam-aws-187-security_group_ingress_is_restricted_3389",
        "epam-aws-255-restrict_outbound_traffic",
        "epam-aws-118-security_group_ingress_is_restricted_traffic_to_pop3_port_110",
        "epam-aws-313-security_group_ingress_is_restricted_traffic_to_port_4333",
        "epam-aws-113-security_group_ingress_is_restricted_traffic_to_microsoft_ds_port_445",
        "epam-aws-332-ec2_instance_no_public_ip",
        "epam-aws-317-security_group_ingress_is_restricted_traffic_to_elasticsearch_service_ports",
        "epam-aws-562-transit_gateway_without_tag_information",
        "epam-aws-557-nat_gateway_without_tag_information",
        "epam-aws-566-vpc_endpoint_without_tag_information",
        "epam-aws-099-instance_without_any_tag",
        "epam-aws-553-eip_without_tag_information",
        "epam-aws-100-ebs-volume_without_recent_snapshot",
        "epam-aws-181-ensure_iam_instance_roles_are_used_for_resource_access_from_instance",
        "epam-aws-117-security_group_ingress_is_restricted_traffic_to_oracle_db_port_1521",
        "epam-aws-555-eni_without_tag_information",
        "epam-aws-318-rds_database_cluster_engine_no_default_ports",
        "epam-aws-111-security_group_ingress_is_restricted_traffic_to_ftp_port_21",
        "epam-aws-222-ami_public_access",
        "epam-aws-315-security_group_ingress_is_restricted_traffic_to_port_5601",
        "epam-aws-410-vpc_endpoint_manual_acceptance",
        "epam-aws-556-internet_gateway_without_tag_information",
        "epam-aws-561-subnet_without_tag_information",
        "epam-aws-331-ec2_stopped_instance",
        "epam-aws-411-unused_virtual_private_gateways",
        "epam-aws-271-alb_with_unencrypted_service_is_exposed_to_public_internet",
        "epam-aws-538-ds_directory_not_open_to_large_scope",
        "epam-aws-269-clb_with_unencrypted_service_is_exposed_to_public_internet",
        "epam-aws-186-security_group_ingress_is_restricted_22",
        "epam-aws-309-security_group_ingress_is_restricted_traffic_to_port_135",
        "epam-aws-265-instance_with_unencrypted_service_is_exposed_to_public_internet",
        "epam-aws-949-key_pair_without_tag_information",
        "epam-aws-563-transit_gateway_attachment_without_tag_information",
        "epam-aws-550-ami_without_tag_information",
    ],
    "aws.ecr": [
        "epam-aws-376-ecr_immutable_image_tags",
        "epam-aws-378-ecr_image_scanning_on_push_enabled",
        "epam-aws-377-ecr_repository_kms_encryption_enabled",
    ],
    "aws.ecs": [
        "epam-aws-906-ecs_containers_readonly_access",
        "epam-aws-690-ecs_exec_logging_enabled",
        "epam-aws-525-ecs_exec_logging_encryption_enabled",
        "epam-aws-955-ecs_containers_nonprivileged",
        "epam-aws-252-ecs_cluster_have_empty_roles_for_service_task_definitions",
        "epam-aws-744-ecs_fargate_latest_platform_version",
        "epam-aws-907-ecs_no_environment_secrets",
        "epam-aws-308-ecs_services_public_ip_addresses_not_assigned_automatically",
        "epam-aws-746-ecs_task_definition_pid_mode_check",
        "epam-aws-743_ecs_container_insights_enabled",
        "epam-aws-336-ecs_task_definitions_secure_networking_modes_and_user_definitions",
        "epam-aws-585-ecs_without_tag_information",
        "epam-aws-244-ecs_cluster_at_rest_encryption",
    ],
    "aws.elasticache": [
        "epam-aws-412-elasticache_no_default_ports",
        "epam-aws-417-elasticache_not_using_default_vpc",
        "epam-aws-420-elasticache_latest_version",
        "epam-aws-259-elasticache_redis_clusters_encryption_at_rest",
        "epam-aws-413-elasticache_previous_generation_instances_not_used",
        "epam-aws-414-elasticache_automatic_backups",
        "epam-aws-588-elasticache_clusters_without_tag_information",
        "epam-aws-415-elasticache_encrypted_in_transit",
        "epam-aws-416-elasticache_encrypted_at_rest_using_cmk",
        "epam-aws-419-elasticache_redis_auth_enabled",
        "epam-aws-418-elasticache_redis_multi_az_enabled",
    ],
    "aws.elasticbeanstalk": [
        "epam-aws-661-elastic_beanstalk_imdsv1_disabled",
        "epam-aws-590-beanstalk_without_tag_information",
        "epam-aws-443-elastic_beanstalk_notifications_enabled",
        "epam-aws-338-elastic_beanstalk_enhanced_health_reporting_enabled",
        "epam-aws-446-elastic_beanstalk_managed_platform_updates",
        "epam-aws-662-elastic_beanstalk_x_ray_enabled",
    ],
    "aws.elasticfilesystem": [
        "epam-aws-257-efs_is_encrypted",
        "epam-aws-337-efs_in_backup_plan",
        "epam-aws-587-efs_without_tag_information",
        "epam-aws-258-efs_is_encrypted_using_managed_cmk",
    ],
    "aws.elasticloadbalancing": [
        "epam-aws-709-clb_cross_zone_load_balancing_enabled",
        "epam-aws-342-alb_http_to_https_redirection_enabled",
        "epam-aws-708-clb-multiple_az",
        "epam-aws-696-alb_desync_mode_check",
        "epam-aws-264-update_security_policy_of_network_load_balancer",
        "epam-aws-101-clb_access_logging_disabled",
        "epam-aws-245-alb_is_protected_by_waf_regional",
        "epam-aws-093-clb_uses_https",
        "epam-aws-268-clb_with_sensitive_service_is_exposed_to_entire_internet",
        "epam-aws-339-alb_drop_invalid_http_header",
        "epam-aws-270-alb_with_sensitive_service_is_exposed_to_entire_internet",
        "epam-aws-591-elb_without_tag_information",
        "epam-aws-294-clb_connection_draining_enabled",
        "epam-aws-263-enable_elb_access_logs",
        "epam-aws-271-alb_with_unencrypted_service_is_exposed_to_public_internet",
        "epam-aws-269-clb_with_unencrypted_service_is_exposed_to_public_internet",
        "epam-aws-341-elb_deletion_protection_enabled",
        "epam-aws-092-remove_weak_ciphers_for_clb",
        "epam-aws-707-clb_desync_mode_check",
        "epam-aws-755-elbv2_multiple_az",
    ],
    "aws.elasticmapreduce": [
        "epam-aws-408-emr_logging_to_s3_enabled",
        "epam-aws-406-emr_at_rest_and_in_transit_encryption_enabled",
        "epam-aws-592-emr_without_tag_information",
        "epam-aws-669-emr_termination_protection_enabled",
        "epam-aws-343-emr_master_nodes_no_public_ip",
        "epam-aws-407-emr_clusters_in_vpc",
        "epam-aws-405-emr_kerberos_authentication_enabled",
    ],
    "aws.es": [
        "epam-aws-425-elasticsearch_slow_logs_enabled",
        "epam-aws-298-elasticsearch_domain_connections_encrypted_using_TLS_1_2",
        "epam-aws-295-elasticsearch_domains_audit_logging_enabled",
        "epam-aws-429-elasticsearch_encrypted_with_kms_cmk",
        "epam-aws-201-elasticsearch_service_domains_encryption_at_rest",
        "epam-aws-297-elasticsearch_domains_configured_with_at_least_three_dedicated_master_nodes",
        "epam-aws-431-elasticsearch_enforces_https",
        "epam-aws-593-elasticsearch_without_tag_information",
        "epam-aws-432-elasticsearch_latest_version",
        "epam-aws-345-elasticsearch_error_logging_to_cloudwatch_enabled",
        "epam-aws-344-elasticsearch_node_to_node_encryption_enabled",
        "epam-aws-769-opensearch_access_control_enabled",
        "epam-aws-200-elasticsearch_service_domains_in_vpc",
        "epam-aws-296-elasticsearch_domains_have_at_least_three_data_nodes",
    ],
    "aws.events": ["epam-aws-453-event_bus_is_exposed_to_everyone"],
    "aws.firehose": [],
    "aws.gamelift": [],
    "aws.glacier": [
        "epam-aws-458-glacier_vault_access_policy_does_not_allow_actions_from_all_principals"
    ],
    "aws.glue": [
        "epam-aws-400-glue_data_catalog_encrypted_at_rest",
        "epam-aws-402-glue_job_bookmarks_encrypted",
        "epam-aws-404-glue_s3_encryption_enabled",
        "epam-aws-532-glue_connection_passwords_encrypted",
        "epam-aws-401-glue_data_catalog_encrypted_with_kms_customer_master_keys",
        "epam-aws-403-glue_cloudwatch_logs_encrypted",
    ],
    "aws.guardduty": ["epam-aws-267-guardduty_service_is_enabled"],
    "aws.health": [],
    "aws.iam": [
        "epam-aws-227-network_access_control_lists_changes_alarm_exists",
        "epam-aws-207-cloudtrail_configuration_changes_alarm_exists",
        "epam-aws-173-iam_password_min_length_ge_14",
        "epam-aws-209-cmk_key_disabling_or_deletion_alarm_exists",
        "epam-aws-098-iam_password_policy_password_reuse",
        "epam-aws-169-ensure_no_root_account_access_key_exists",
        "epam-aws-182-ensure_support_role_created_to_manage_incidents",
        "epam-aws-497-lambda_active_tracing_enabled",
        "epam-aws-097-iam_users_receive_permissions_only_through_groups",
        "epam-aws-204-sign_in_without_mfa_alarm_exist",
        "epam-aws-780-sns_topic_message_delivery_notification_enabled",
        "epam-aws-252-ecs_cluster_have_empty_roles_for_service_task_definitions",
        "epam-aws-170-iam_password_policy_one_lowercase_letter",
        "epam-aws-174-iam_password_policy_passwd_expires_le_90",
        "epam-aws-225-aws_config_configuration_changes_alarm_exists",
        "epam-aws-608-iam_user_without_tag_information",
        "epam-aws-226-security_group_changes_alarm_exists",
        "epam-aws-213-lambda_with_admin_privileges",
        "epam-aws-205-root_usage_alarm_exists",
        "epam-aws-208-console_auth_failure_alarm_exists",
        "epam-aws-277-only_one_active_access_key_available_for_any_single_iam_user",
        "epam-aws-224-s3_bucket_policy_changes_alarm_exists",
        "epam-aws-206-iam_policy_changes_alarm_exist",
        "epam-aws-609-iam_role_without_tag_information",
        "epam-aws-247-managed_policies_instead_of_inline_iam_policies",
        "epam-aws-172-iam_password_policy_one_number",
        "epam-aws-094-ensure_mfa_is_enabled_for_the_root_account",
        "epam-aws-168-iam_password_policy_one_uppercase_letter",
        "epam-aws-180-iam_user_with_password_and_unused_access_keys",
        "epam-aws-760-iam_group_has_users_check",
        "epam-aws-178-iam_policies_full_administrative_privileges",
        "epam-aws-002-ensure_mfa_is_enabled_for_all_iam_users_with_console_password",
        "epam-aws-171-iam_password_policy_one_symbol",
        "epam-aws-230-vpc_changes_alarm_exists",
        "epam-aws-095-ensure_hardware_mfa_is_enabled_for_root_account",
        "epam-aws-835-inactive_iam_access_keys_are_not_deleted",
        "epam-aws-192-unauthorized_api_calls_alarm_exists",
        "epam-aws-228-network_gateways_changes_alarm_exists",
        "epam-aws-229-route_table_changes_alarm_exists",
    ],
    "aws.iot": [],
    "aws.kinesis": [
        "epam-aws-254-kinesis_server_data_at_rest_has_sse",
        "epam-aws-613-kinesis_data_stream_without_tag_information",
        "epam-aws-239-kinesis_streams_keys_are_rotated",
        "epam-aws-253-kinesis_streams_encrypted_kms_customer_master_keys",
    ],
    "aws.kms": [
        "epam-aws-615-kms_key_without_tag_information",
        "epam-aws-911-kms_cmk_not_scheduled_for_deletion",
        "epam-aws-256-dynamodb_is_encrypted_using_managed_cmk",
        "epam-aws-253-kinesis_streams_encrypted_kms_customer_master_keys",
        "epam-aws-258-efs_is_encrypted_using_managed_cmk",
    ],
    "aws.lambda": [
        "epam-aws-366-secrets_manager_successful_rotation_check",
        "epam-aws-212-lambda_in_vpc",
        "epam-aws-213-lambda_with_admin_privileges",
        "epam-aws-681-lambda_concurrency_enabled",
        "epam-aws-616-lambda_functions_without_tag_information",
        "epam-aws-678-lambda_code_signing_enabled",
        "epam-aws-953-lambda_function_settings_check",
        "epam-aws-500-lambda_variables_encrypted_with_kms_cmk",
        "epam-aws-497-lambda_active_tracing_enabled",
        "epam-aws-365-secrets_manager_rotation_enabled",
    ],
    "aws.logs": [
        "epam-aws-227-network_access_control_lists_changes_alarm_exists",
        "epam-aws-207-cloudtrail_configuration_changes_alarm_exists",
        "epam-aws-209-cmk_key_disabling_or_deletion_alarm_exists",
        "epam-aws-618-cloudwatch_log_groups_without_tag_information",
        "epam-aws-356-rds_aurora_postgresql_logging_enabled",
        "epam-aws-715-cloudwatch_log_group_encrypted_with_kms_cmk",
        "epam-aws-349-rds_oracle_logging_enabled",
        "epam-aws-204-sign_in_without_mfa_alarm_exist",
        "epam-aws-355-rds_aurora_mysql_logging_enabled",
        "epam-aws-352-rds_mariadb_logging_enabled",
        "epam-aws-225-aws_config_configuration_changes_alarm_exists",
        "epam-aws-226-security_group_changes_alarm_exists",
        "epam-aws-205-root_usage_alarm_exists",
        "epam-aws-208-console_auth_failure_alarm_exists",
        "epam-aws-224-s3_bucket_policy_changes_alarm_exists",
        "epam-aws-206-iam_policy_changes_alarm_exist",
        "epam-aws-345-elasticsearch_error_logging_to_cloudwatch_enabled",
        "epam-aws-353-rds_sql_server_logging_enabled",
        "epam-aws-354-rds_aurora_logging_enabled",
        "epam-aws-230-vpc_changes_alarm_exists",
        "epam-aws-350-rds_postgresql_logging_enabled",
        "epam-aws-192-unauthorized_api_calls_alarm_exists",
        "epam-aws-228-network_gateways_changes_alarm_exists",
        "epam-aws-229-route_table_changes_alarm_exists",
        "epam-aws-351-rds_mysql_logging_enabled",
    ],
    "aws.monitoring": [
        "epam-aws-227-network_access_control_lists_changes_alarm_exists",
        "epam-aws-207-cloudtrail_configuration_changes_alarm_exists",
        "epam-aws-204-sign_in_without_mfa_alarm_exist",
        "epam-aws-225-aws_config_configuration_changes_alarm_exists",
        "epam-aws-209-cmk_key_disabling_or_deletion_alarm_exists",
        "epam-aws-226-security_group_changes_alarm_exists",
        "epam-aws-205-root_usage_alarm_exists",
        "epam-aws-208-console_auth_failure_alarm_exists",
        "epam-aws-230-vpc_changes_alarm_exists",
        "epam-aws-192-unauthorized_api_calls_alarm_exists",
        "epam-aws-224-s3_bucket_policy_changes_alarm_exists",
        "epam-aws-206-iam_policy_changes_alarm_exist",
        "epam-aws-228-network_gateways_changes_alarm_exists",
        "epam-aws-229-route_table_changes_alarm_exists",
    ],
    "aws.opsworks": [],
    "aws.opsworks-cm": [],
    "aws.qldb": [
        "epam-aws-644-qldb_deletion_protection_enabled",
        "epam-aws-643-qldb_permission_mode_is_standard",
        "epam-aws-624-qldb_ledgers_without_tag_information",
    ],
    "aws.rds": [
        "epam-aws-346-rds_instance_enhanced_monitoring_enabled",
        "epam-aws-357-rds_instance_iam_authentication_configured",
        "epam-aws-082-rds_retention_backup_is_at_least_7_days",
        "epam-aws-770-rds_automatic_minor_version_upgrade_enabled",
        "epam-aws-083-rds_high-availability_zone",
        "epam-aws-299-rds_db_clusters_configured_to_copy_tags_to_snapshots",
        "epam-aws-381-postgresql_debug_print_parse_flag_disabled",
        "epam-aws-140-rds_without_tag_information",
        "epam-aws-358-rds_cluster_iam_authentication_configured",
        "epam-aws-385-postgresql_log_connections_flag_enabled",
        "epam-aws-424-rds_aurora_postgresql_cluster_logging_enabled",
        "epam-aws-445-rds_mysql_instances_latest_major_version",
        "epam-aws-455-postgresql_log_executor_stats_flag_disabled",
        "epam-aws-320-rds_snapshots_storage_is_encrypted",
        "epam-aws-421-documentdb_logging_enabled",
        "epam-aws-356-rds_aurora_postgresql_logging_enabled",
        "epam-aws-626-rds_snapshot_without_tag_information",
        "epam-aws-457-postgresql_log_min_error_statement_flag_set_correctly",
        "epam-aws-301-rds_critical_cluster_events_notification_exists",
        "epam-aws-422-rds_aurora_cluster_logging_enabled",
        "epam-aws-319-rds_instances_storage_is_encrypted",
        "epam-aws-349-rds_oracle_logging_enabled",
        "epam-aws-219-rds_snapshot_prohibit_public_access",
        "epam-aws-304-rds_database_security_group_events_notification_exists",
        "epam-aws-478-oracle_sec_return_server_release_banner_flag_disabled",
        "epam-aws-302-rds_database_instance_events_notification_exists",
        "epam-aws-360-rds_cluster_multi_az_enabled",
        "epam-aws-386-postgresql_log_disconnections_flag_enabled",
        "epam-aws-261-rds_cluster_storage_is_encrypted",
        "epam-aws-303-rds_database_parameter_group_events_notification_exists",
        "epam-aws-355-rds_aurora_mysql_logging_enabled",
        "epam-aws-318-rds_database_cluster_engine_no_default_ports",
        "epam-aws-479-oracle_sql92_security_flag_enabled",
        "epam-aws-081-rds_not_open_to_large_scope",
        "epam-aws-515-rds_encrypted_with_kms_cmk",
        "epam-aws-359-rds_aurora_mysql_backtracking_enabled",
        "epam-aws-291-rds_public_access_disabled",
        "epam-aws-454-postgresql_log_planner_stats_flag_disabled",
        "epam-aws-352-rds_mariadb_logging_enabled",
        "epam-aws-351-rds_mysql_logging_enabled",
        "epam-aws-472-oracle_audit_trail_flag_set_correctly",
        "epam-aws-305-rds_database_instance_engine_no_default_ports",
        "epam-aws-387-postgresql_log_error_verbosity_flag_set_correctly",
        "epam-aws-451-postgresql_log_parser_stats_flag_is_disabled",
        "epam-aws-423-rds_aurora_mysql_cluster_logging_enabled",
        "epam-aws-384-postgresql_debug_pretty_print_flag_enabled",
        "epam-aws-475-oracle_sec_max_failed_login_attempts_flag_is_3_or_less",
        "epam-aws-773-rds_instance_default_admin_check",
        "epam-aws-392-postgresql_log_lock_waits_flag_enabled",
        "epam-aws-476-oracle_sec_protocol_error_further_action_flag_set_to_drop_3",
        "epam-aws-389-postgresql_log_statement_flag_set_correctly",
        "epam-aws-477-oracle_sec_protocol_error_trace_action_flag_set_to_log",
        "epam-aws-393-postgresql_log_duration_flag_enabled",
        "epam-aws-382-postgresql_debug_print_rewritten_flag_disabled",
        "epam-aws-771-rds_cluster_default_admin_check",
        "epam-aws-625-rds_cluster_without_tag_information",
        "epam-aws-492-mysql_sql_mode_flag_contains_strict_all_tables",
        "epam-aws-474-oracle_remote_listener_flag_empty",
        "epam-aws-347-rds_cluster_deletion_protection_enabled",
        "epam-aws-380-postgresql_log_rotation_size_flag_set_correctly",
        "epam-aws-353-rds_sql_server_logging_enabled",
        "epam-aws-390-postgresql_log_destination_flag_set_to_csvlog",
        "epam-aws-471-oracle_audit_sys_operations_flag_enabled",
        "epam-aws-473-oracle_global_names_flag_enabled",
        "epam-aws-354-rds_aurora_logging_enabled",
        "epam-aws-383-postgresql_debug_print_plan_flag_disabled",
        "epam-aws-350-rds_postgresql_logging_enabled",
        "epam-aws-379-postgresql_log_rotation_age_flag_set_to_60",
        "epam-aws-391-postgresql_log_checkpoints_flag_enabled",
        "epam-aws-388-postgresql_log_hostname_flag_disabled",
        "epam-aws-300-rds_db_instances_configured_to_copy_tags_to_snapshots",
        "epam-aws-348-rds_instance_deletion_protection_enabled",
        "epam-aws-481-oracle_resource_limit_flag_enabled",
        "epam-aws-480-oracle_trace_files_public",
    ],
    "aws.redshift": [
        "epam-aws-627-redshift_clusters_without_tag_information",
        "epam-aws-521-redshift_parameter_group_require_ssl",
        "epam-aws-517-redshift_user_activity_logging_enabled",
        "epam-aws-519-redshift_not_using_default_port",
        "epam-aws-362-redshift_cluster_automatic_snapshot_enabled",
        "epam-aws-306-redshift_clusters_audit_logging_enabled",
        "epam-aws-520-redshift_encrypted_with_kms_cmk",
        "epam-aws-657-redshift_availability_zone_relocation_enabled",
        "epam-aws-260-redshift_instances_are_encrypted",
        "epam-aws-776-redshift_default_admin_check",
        "epam-aws-777-redshift_default_db_name_check",
        "epam-aws-361-redshift_cluster_encrypted_in_transit",
        "epam-aws-363-redshift_cluster_automatic_upgrade_to_major_version_enabled",
        "epam-aws-215-redshift_cluster_prohibit_public_access",
        "epam-aws-364-redshift_cluster_enhanced_vpc_routing_enabled",
    ],
    "aws.route53": ["epam-aws-513-route53_query_logging_enabled"],
    "aws.s3": [
        "epam-aws-227-network_access_control_lists_changes_alarm_exists",
        "epam-aws-207-cloudtrail_configuration_changes_alarm_exists",
        "epam-aws-899-s3_event_notifications_enabled",
        "epam-aws-162-s3_bucket_lifecycle",
        "epam-aws-209-cmk_key_disabling_or_deletion_alarm_exists",
        "epam-aws-141-s3_encrypted_using_kms",
        "epam-aws-286-bucket_employ_encryption_at_rest",
        "epam-aws-211-cloudtrail_bucket_logging_enabled",
        "epam-aws-204-sign_in_without_mfa_alarm_exist",
        "epam-aws-282-bucket_object-level_logging_for_write_enabled",
        "epam-aws-163-s3_buckets_without_tags",
        "epam-aws-194-s3_bucket_should_not_allow_all_actions_from_all_principals",
        "epam-aws-900-s3_bucket_acl_prohibited",
        "epam-aws-193-s3_bucket_cloudtrail_logs_not_publicly_accessible",
        "epam-aws-535-s3_bucket_enforces_sse",
        "epam-aws-689-bucket_not_dns_compliant",
        "epam-aws-283-bucket_object-level_logging_for_read_enabled",
        "epam-aws-225-aws_config_configuration_changes_alarm_exists",
        "epam-aws-642-s3_bucket_object_lock_enabled",
        "epam-aws-226-security_group_changes_alarm_exists",
        "epam-aws-216-s3_bucket_cross_region_replication_enabled",
        "epam-aws-205-root_usage_alarm_exists",
        "epam-aws-280-s3_buckets_configured_with_block_public_access",
        "epam-aws-208-console_auth_failure_alarm_exists",
        "epam-aws-224-s3_bucket_policy_changes_alarm_exists",
        "epam-aws-206-iam_policy_changes_alarm_exist",
        "epam-aws-080-bucket_policy_allows_https_requests",
        "epam-aws-246-s3_bucket_versioning_mfa_delete_enabled",
        "epam-aws-290-logging_for_s3_enabled",
        "epam-aws-228-network_gateways_changes_alarm_exists",
        "epam-aws-230-vpc_changes_alarm_exists",
        "epam-aws-192-unauthorized_api_calls_alarm_exists",
        "epam-aws-901-s3_version_lifecycle_policy_check",
        "epam-aws-229-route_table_changes_alarm_exists",
    ],
    "aws.sagemaker": [
        "epam-aws-499-sagemaker_endpoint_configuration_encrypted",
        "epam-aws-501-sagemaker_instance_root_disabled",
        "epam-aws-464-sagemaker_instances_encrypted_with_kms_cmk",
        "epam-aws-232-sagemaker_does_not_have_direct_internet_access",
        "epam-aws-223-ensure_that_sagemaker_in_vpc",
        "epam-aws-504-sagemaker_network_isolation_enabled",
    ],
    "aws.secretsmanager": [
        "epam-aws-366-secrets_manager_successful_rotation_check",
        "epam-aws-365-secrets_manager_rotation_enabled",
    ],
    "aws.servicecatalog": [],
    "aws.sns": [
        "epam-aws-227-network_access_control_lists_changes_alarm_exists",
        "epam-aws-207-cloudtrail_configuration_changes_alarm_exists",
        "epam-aws-209-cmk_key_disabling_or_deletion_alarm_exists",
        "epam-aws-711-cloudformation_stack_notification_check",
        "epam-aws-204-sign_in_without_mfa_alarm_exist",
        "epam-aws-780-sns_topic_message_delivery_notification_enabled",
        "epam-aws-516-sns_encrypted_with_kms_cmk",
        "epam-aws-368-sns_kms_encryption_enabled",
        "epam-aws-559-route_table_without_tag_information",
        "epam-aws-225-aws_config_configuration_changes_alarm_exists",
        "epam-aws-226-security_group_changes_alarm_exists",
        "epam-aws-205-root_usage_alarm_exists",
        "epam-aws-208-console_auth_failure_alarm_exists",
        "epam-aws-224-s3_bucket_policy_changes_alarm_exists",
        "epam-aws-632-sns_without_tag_information",
        "epam-aws-206-iam_policy_changes_alarm_exist",
        "epam-aws-230-vpc_changes_alarm_exists",
        "epam-aws-192-unauthorized_api_calls_alarm_exists",
        "epam-aws-228-network_gateways_changes_alarm_exists",
        "epam-aws-229-route_table_changes_alarm_exists",
    ],
    "aws.sqs": [
        "epam-aws-447-sqs_encrypted_with_kms_cmk",
        "epam-aws-633-sqs_without_tag_information",
        "epam-aws-102-ensures_sqs_encryption_is_enabled",
        "epam-aws-449-sqs_not_open_to_everyone",
        "epam-aws-450-sqs_dead_letter_queue_enabled",
    ],
    "aws.ssm": [
        "epam-aws-221-ec2_managed_ssm_patch_compliance",
        "epam-aws-370-ec2_instance_managed_by_systems_manager",
        "epam-aws-371-ec2_managed_instance_association_compliance_status_check",
    ],
    "aws.states": [],
    "aws.storagegateway": [],
    "aws.support": [],
    "aws.swf": [],
    "aws.waf": [
        "epam-aws-245-alb_is_protected_by_waf_regional",
        "epam-aws-917-waf_global_webacl_not_empty",
    ],
    "aws.waf-regional": ["epam-aws-396-rest_api_gateway_is_protected_by_waf"],
    "aws.workspaces": [
        "epam-aws-548-workspaces_storage_encrypted_with_cmk",
        "epam-aws-494-workspaces_web_access_disabled",
        "epam-aws-542-workspaces_maintenance_mode_enabled",
        "epam-aws-439-workspaces_storage_encrypted",
        "epam-aws-546-workspaces_radius_server_uses_strongest_security_protocol",
        "epam-aws-545-workspaces_api_requests_flow_through_vpc_endpoint",
        "epam-aws-541-workspaces_cloudwatch_integration",
        "epam-aws-543-workspaces_primary_interface_ports_not_open_to_all_inbound_traffic",
    ],
    "aws.xray": ["epam-aws-434-xray-encrypted_with_kms_cmk"],
}
