[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "srecli"
description = "Syndicate Rule Engine CLI"
requires-python = ">=3.14,<4"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "click>=8.3,<9",
    "tabulate>=0.10,<1",
    "boto3>=1.26.80,<2",
    "python-dateutil>=2.9,<3",
    "modular-cli-sdk[hvac] @ git+https://github.com/epam/modular-cli-sdk@feature/python_314#egg=modular-cli-sdk==3.1.5",
]

[project.scripts]
sre = "srecli.group.sre:sre"

[tool.setuptools.dynamic]
version = {attr = "srecli.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["srecli*"]
exclude = ["srecli_tests*"]
namespaces = false

[tool.pyright]
include = ["srecli"]
exclude = [
    "**/__pycache__",
]
pythonVersion = "3.14"
reportIncompatibleMethodOverride = "warning"
