memoryLimit: 64Mi
memoryRequest: 32Mi

service:
  type: ClusterIP
  port: 6380  # 6379 is taken by Defect Dojo
  nodePort: 32104

image:
  repository: valkey/valkey
  tag: "8.0.10-alpine"
  pullPolicy: IfNotPresent

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: standard
  # Retain the former Redis data path and resource name during upgrades.
  hostPath: /data/redis
  existingName: "redis"

replicas: 1
strategy:
  type: Recreate
  maxUnavailable: 0
  maxSurge: 100%
