FROM public.ecr.aws/docker/library/python:3.10 as compile-image

ARG CUSTODIAN_SERVICE_PATH=.
ARG CLOUD_CUSTODIAN_PACKAGE="c7n~=0.9.43"
ARG CLOUD_CUSTODIAN_PROVIDERS="c7n-gcp~=0.4.42 c7n-azure~=0.7.42 c7n-kube~=0.2.42"

RUN python3 -m venv /venv

RUN /venv/bin/pip install "$CLOUD_CUSTODIAN_PACKAGE" && for pkg in $CLOUD_CUSTODIAN_PROVIDERS; do /venv/bin/pip install "$pkg"; done

COPY $CUSTODIAN_SERVICE_PATH/src/onprem/requirements.txt /src/onprem/requirements.txt
RUN /venv/bin/pip install -r /src/onprem/requirements.txt

COPY $CUSTODIAN_SERVICE_PATH/src /src
RUN chmod +x /src/entrypoint.sh /src/main.py && \
    rm -f /src/.env.example /src/executor/Dockerfile* /src/executor/requirements.txt /src/onprem/Dockerfile* /src/onprem/requirements.txt


FROM public.ecr.aws/docker/library/python:3.10-slim AS build-image

ARG USERNAME=sre

RUN groupadd --gid=1337 $USERNAME && \
    useradd --system --uid=1001 --gid=1337 --no-create-home $USERNAME

COPY --from=compile-image --chown=$USERNAME:$USERNAME /venv /venv
COPY --from=compile-image --chown=$USERNAME:$USERNAME /src /src

WORKDIR /src
USER $USERNAME
ENV AWS_REGION=us-east-1 \
    CAAS_SERVICE_MODE=docker \
    modular_service_mode=docker \
    PATH=/venv/bin:$PATH
EXPOSE 8000
ENTRYPOINT ["/src/entrypoint.sh"]
