FROM public.ecr.aws/docker/library/python:3.10-slim as compile-image

ARG CUSTODIAN_SERVICE_PATH=.
ARG CLOUD_CUSTODIAN_PROVIDERS="gcp azure kube"

# some dependency error occurred when installing all with one pip install command. So
RUN pip install --user c7n && for pkg in $CLOUD_CUSTODIAN_PROVIDERS; do pip install --user c7n-$pkg; done

COPY $CUSTODIAN_SERVICE_PATH/src/executor/requirements.txt /src/executor/requirements.txt
RUN pip install --user -r /src/executor/requirements.txt

COPY $CUSTODIAN_SERVICE_PATH/src/onprem/requirements.txt /src/onprem/requirements.txt
RUN pip install --user -r /src/onprem/requirements.txt

COPY $CUSTODIAN_SERVICE_PATH/src /src

RUN rm -rf $(find /root/.local/lib -name "*.dist-info") && rm -rf $(find /root/.local/lib/ -name "__pycache__")


FROM public.ecr.aws/docker/library/python:3.10-slim AS build-image

COPY --from=compile-image /root/.local /root/.local
COPY --from=compile-image /src /src

ENV AWS_REGION=us-east-1 \
    CAAS_SERVICE_MODE=docker \
    PATH=/root/.local/bin:$PATH \
    modular_service_mode=docker

WORKDIR /src
EXPOSE 8000
RUN chmod +x entrypoint.sh main.py
ENTRYPOINT ["/src/entrypoint.sh"]
