FROM public.ecr.aws/docker/library/python:3.10 as compile-image

ARG CUSTODIAN_SERVICE_PATH=.
ARG CLOUD_CUSTODIAN_PACKAGE="c7n~=0.9.43"
ARG CLOUD_CUSTODIAN_PROVIDERS="c7n-gcp~=0.4.42 c7n-azure~=0.7.42 c7n-kube~=0.2.42"

# some dependency error occurred when installing all with one pip install command. So
RUN pip install --user "$CLOUD_CUSTODIAN_PACKAGE" && for pkg in $CLOUD_CUSTODIAN_PROVIDERS; do pip install --user "$pkg"; done

COPY $CUSTODIAN_SERVICE_PATH/src/onprem/requirements.txt /src/onprem/requirements.txt
RUN pip install --user -r /src/onprem/requirements.txt

COPY $CUSTODIAN_SERVICE_PATH/src /src


FROM public.ecr.aws/docker/library/python:3.10-slim AS build-image

COPY --from=compile-image /root/.local /root/.local
COPY --from=compile-image /src /src

ENV AWS_REGION=us-east-1 \
    CAAS_SERVICE_MODE=docker \
    PATH=/root/.local/bin:$PATH \
    modular_service_mode=docker

WORKDIR /src
EXPOSE 8000
RUN chmod +x entrypoint.sh main.py
ENTRYPOINT ["/src/entrypoint.sh"]
